# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^bin/."
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
      exclude: "^.*goss.yml$"
    - id: check-added-large-files
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
-   repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
    - id: beautysh
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
    - id: shellcheck
      args: ["-e", "SC1091", "-e", "SC2219", "-e", "SC2004"]
